# Generated by Django 3.2.3 on 2021-05-29 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trashcount',
            old_name='used_id',
            new_name='user_id',
        ),
    ]
